services:
  darkside.leasingcalc.ui:
    image: ${DOCKER_REGISTRY-}darksideleasingcalcui
    networks:
      - darkside
    build:
      context: .
      dockerfile: Darkside.LeasingCalc.UI/Dockerfile

  darksideleasing.app.api:
    image: ${DOCKER_REGISTRY-}darksideleasingappapi
    networks:
      - darkside
    build:
      context: DarkSideLeasing.App.Api
      dockerfile: Dockerfile

  darkside.leasingcalc.db:
     image: mcr.microsoft.com/mssql/server:2022-latest
     networks:
      - darkside
     ports:
      - 3629:1433
     volumes:
      - darkside-leasing-volume:/var/opt/mssql/darksideleasing
     environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=myPassword123


  darksideleasing.app.queue:
    image: ${DOCKER_REGISTRY-}darksideleasingappqueue
    networks:
      - darkside
    build:
      context: .
      dockerfile: DarksideLeasing.App.Queue/Dockerfile

volumes:
  darkside-leasing-volume:
    external: true

networks:
    darkside:
      driver: bridge
