// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class DocumentRequest
{
    public Guid RequestId { get; set; }

    public Guid TemplateId { get; set; }

    public Guid RequestedByUserId { get; set; }

    public DateTime RequestedOn { get; set; }

    public string Status { get; set; }

    public string GeneratedUrl { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ICollection<FieldValue> FieldValues { get; set; } = new List<FieldValue>();

    public virtual User RequestedByUser { get; set; }

    public virtual Template Template { get; set; }
}