// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class FieldValue
{
    public Guid FieldValueId { get; set; }

    public Guid RequestId { get; set; }

    public string FieldName { get; set; }

    public string Value { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual DocumentRequest Request { get; set; }
}