// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Darkside.Logging.Datas.Models;

public partial class GPSDocumentGenieDataContext : DbContext
{
    public GPSDocumentGenieDataContext(DbContextOptions<GPSDocumentGenieDataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Log> Logs { get; set; }

    

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Log>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Logs__3214EC071A385806");

            entity.HasIndex(e => e.LogLevel, "IX_Logs_LogLevel");

            entity.HasIndex(e => e.Timestamp, "IX_Logs_Timestamp");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Application).HasMaxLength(100);
            entity.Property(e => e.CreatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.LogLevel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Module).HasMaxLength(100);
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(sysutcdatetime())");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}