// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class Log
{
    public Guid Id { get; set; }

    public DateTime Timestamp { get; set; }

    public string LogLevel { get; set; }

    public string Application { get; set; }

    public string Module { get; set; }

    public Guid? TenantId { get; set; }

    public string Message { get; set; }

    public string Exception { get; set; }

    public string Properties { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Tenant Tenant { get; set; }
}