// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class Plan
{
    public Guid PlanId { get; set; }

    public string Name { get; set; }

    public decimal PricePerMonth { get; set; }

    public int MaxDocuments { get; set; }

    public int? MaxUsers { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ICollection<TenantSubscription> TenantSubscriptions { get; set; } = new List<TenantSubscription>();
}