// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class Template
{
    public Guid TemplateId { get; set; }

    public Guid TenantId { get; set; }

    public string Name { get; set; }

    public string StorageUrl { get; set; }

    public string FieldMetadataJson { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ICollection<DocumentRequest> DocumentRequests { get; set; } = new List<DocumentRequest>();

    public virtual Tenant Tenant { get; set; }
}