// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class Tenant
{
    public Guid TenantId { get; set; }

    public string TenantName { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ICollection<BillingHistory> BillingHistories { get; set; } = new List<BillingHistory>();

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual ICollection<Template> Templates { get; set; } = new List<Template>();

    public virtual ICollection<TenantSubscription> TenantSubscriptions { get; set; } = new List<TenantSubscription>();

    public virtual ICollection<UploadFile> UploadFiles { get; set; } = new List<UploadFile>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}