// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class UploadFile
{
    public Guid UploadFileId { get; set; }

    public string Status { get; set; }

    public Guid? TemplateId { get; set; }

    public Guid? UserId { get; set; }

    public string GeneratedUrl { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public Guid? TenantId { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual Tenant Template { get; set; }

    public virtual User User { get; set; }
}