// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Darkside.Logging.Datas.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public Guid TenantId { get; set; }

    public string Email { get; set; }

    public string Role { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ICollection<DocumentRequest> DocumentRequests { get; set; } = new List<DocumentRequest>();

    public virtual Tenant Tenant { get; set; }

    public virtual ICollection<UploadFile> UploadFiles { get; set; } = new List<UploadFile>();
}