<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>50b3d6cb-a55a-476b-a0e7-5bb476e12474</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Darkside.Logger.Client\Darkside.Logger.Client.csproj" />
    <ProjectReference Include="..\Darkside.Logger.Contracts\Darkside.Logger.Contracts.csproj" />
  </ItemGroup>

</Project>
