name: DarkSide Leasing UI

env:
  AZURE_WEBAPP_NAME: darksideleasing-dev-ui    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: './Darkside.LeasingCalc.UI'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Darkside.LeasingCalc.UI/Darkside.LeasingCalc.UI.csproj

    - name: Build
      run: dotnet build ./Darkside.LeasingCalc.UI/Darkside.LeasingCalc.UI.csproj --configuration Release

    - name: Publish
      run: dotnet publish ./Darkside.LeasingCalc.UI/Darkside.LeasingCalc.UI.csproj --configuration Release --output ./publish

    - name: Zip published output
      run: zip -r publish.zip ./publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
          name: .net-app
          path: publish.zip

    - name: Show folder structure
      run: |
        echo "Displaying folder structure for folder 'your-folder-name'"
        tree ${{ github.workspace }}/publish

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish.zip
          slot-name: production
