# .github/workflows/main_workflow.yml
name: Main Workflow

on:
  workflow_dispatch:

jobs:
  deploy_iac:
    uses: ./.github/workflows/deploy_iac.yml

  deploy_api:
    needs: deploy_iac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Azure Login
        if: failure()
        run: |
          echo "Azure login failed"
          echo "Credentials: ${{ secrets.AZURE_CREDENTIALS }}"

      - name: Verify Azure Login
        run: az account show

      - name: Deploy API
        run: echo "Deploying API..." # Replace with actual deployment steps

  deploy_queue:
    needs: deploy_iac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug Azure Login
        if: failure()
        run: |
          echo "Azure login failed"
          echo "Credentials: ${{ secrets.AZURE_CREDENTIALS }}"

      - name: Verify Azure Login
        run: az account show

      - name: Deploy Queue
        run: echo "Deploying Queue..." # Replace with actual deployment steps
